apiVersion: apps/v1
kind: Deployment
metadata:
    name: settlement 
    labels:
        app: settlement
spec:
    replicas: 1
    selector:
        matchLabels:
            app: settlement
    template:
        metadata:
            labels:
                app: settlement
        spec:
            containers:
            - name: settlement
              image: 712351274497.dkr.ecr.ap-northeast-2.amazonaws.com/settlement
              ports:
              - containerPort: 8086
              resources:
                  requests:
                      cpu: "1000m"
                  limits:
                      cpu: "1000m"