apiVersion: v1
kind: Service
metadata:
    name: settlement
    labels:
        run: settlement
spec:
    ports:
    - port: 8086
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
    selector:
        run: settlement
    type: LoadBalancer 
