apiVersion: apps/v1
kind: Deployment
metadata:
    name: settlement 
    labels:
        app: settlement
spec:
    replicas: 1
    selector:
        matchLabels:
            app: settlement
    template:
        metadata:
            labels:
                app: settlement
        spec:
            containers:
            - name: settlement
              image: hyeonjaecho/settlement
              ports:
              - containerPort: 8086
