apiVersion: v1
kind: Service
metadata:
    name: settlement
    labels:
        run: settlement
spec:
    ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: http
    selector:
        run: settlement
    type: LoadBalancer 
