database: h2 

spring:
  application:
    name: settlement
  profiles:
    active: default
  sql:
    init:
      mode: embedded # ALWAYS: 모든 데이터베이스에 sql 스크립트를 동작시킨다. / EMBDEDED: embedded 데이터베이스만 sql 스크립트를 동작시킨다. / NEVER: 모든 데이터베이스에 sql 스크립트를 동작시키지 않는다.
      #schema-locations: classpath*:db/${database}/schema.sql
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
#-------------------------------------------------------------
# Kafka 설정
#-------------------------------------------------------------
  cloud:
    function:
      #definition: wheneverContractCompletedThenCreateSettlement;wheneverContractAcceptedThenCreateContract;wheneverPaymentCompletedThenCreatePayment;
      definition: basicConsumer
      
    stream:
      kafka:
        #binder:
        #  brokers: localhost:9091,localhost:9092,localhost:9093
        #  zkNodes: localhost:2181,localhost:2182,localhost:2183
        binder:
          brokers: localhost:9092
        
      bindings:
        basicConsumer-in-0:
          group: contract
          destination: caremoa-topic
          content-type: application/json
        #basicProducer-out-0:
        #  destination: caremoa-topic
        #  content-type: application/json

server:
  port: 8086

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        
  
logging:
  level:
    root: debug
    org.hibernate.SQL: debug